

import type { LucideIcon } from 'lucide-react';
import {
  Image,
  FileText,
  Mic,
  Palette,
  Ruler,
  QrCode,
  Sigma,
  CaseSensitive,
  Link,
  Calendar,
  Calculator,
  Lock,
  FileCode,
  Braces,
  Hash,
  Binary,
  BookType,
  Clock,
  Crop,
  Percent,
  Landmark,
  Barcode,
  Sparkles,
  Merge,
  RotateCw,
  Trash2,
  Split,
  Shield,
  SquarePen,
  FileScan,
  FileKey2,
} from 'lucide-react';

export type ToolCategory = "Text & Data" | "Image & Media" | "Calculators" | "Generators" | "PDF";

export type Tool = {
  id: string;
  name: string;
  description: string;
  href: string;
  icon: LucideIcon;
  category: ToolCategory;
};

export const tools: Tool[] = [
  {
    id: 'image-compressor',
    name: 'Image Compressor Online',
    description: 'Reduce JPG, PNG, WEBP, and GIF file sizes without losing quality. Fast and free.',
    href: '/tools/image-compressor',
    icon: Image,
    category: 'Image & Media',
  },
  {
    id: 'ai-background-remover',
    name: 'AI Background Remover',
    description: 'Automatically remove the background from any image with a single click. 100% free and private.',
    href: '/tools/ai-background-remover',
    icon: FileScan,
    category: 'Image & Media',
  },
  {
    id: 'image-resizer',
    name: 'Image Resizer',
    description: 'Resize images to specific dimensions (width and height) online. Simple and fast.',
    href: '/tools/image-resizer',
    icon: Crop,
    category: 'Image & Media',
  },
  {
    id: 'pdf-maker',
    name: 'PDF Maker from Images',
    description: 'Convert JPG and PNG images into a single, downloadable PDF file. 100% private.',
    href: '/tools/pdf-maker',
    icon: FileText,
    category: 'PDF',
  },
  {
    id: 'pdf-to-word-converter',
    name: 'PDF to Word Converter',
    description: 'Convert PDF files to editable Word documents. (Coming Soon)',
    href: '/tools/pdf-to-word-converter',
    icon: FileKey2,
    category: 'PDF',
  },
  {
    id: 'pdf-merger',
    name: 'Merge PDF',
    description: 'Combine multiple PDF documents into one single file. Secure and client-side.',
    href: '/tools/pdf-merger',
    icon: Merge,
    category: 'PDF',
  },
  {
    id: 'pdf-rotator',
    name: 'Rotate PDF',
    description: 'Rotate pages in a PDF document individually. Processed securely in your browser.',
    href: '/tools/pdf-rotator',
    icon: RotateCw,
    category: 'PDF',
  },
  {
    id: 'pdf-deleter',
    name: 'Delete PDF Pages',
    description: 'Remove one or more pages from a PDF document. Fast, private, and simple to use.',
    href: '/tools/pdf-deleter',
    icon: Trash2,
    category: 'PDF',
  },
    {
    id: 'pdf-splitter',
    name: 'Split PDF',
    description: 'Extract specific pages from a PDF document into a new file. 100% secure.',
    href: '/tools/pdf-splitter',
    icon: Split,
    category: 'PDF',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark to PDF',
    description: 'Add a text watermark to your PDF files with customizable opacity and rotation.',
    href: '/tools/add-watermark',
    icon: SquarePen,
    category: 'PDF',
  },
  {
    id: 'text-to-speech',
    name: 'Text to Speech Online',
    description: 'Convert any text into natural-sounding speech with various voice controls. Free online TTS tool.',
    href: '/tools/text-to-speech',
    icon: Mic,
    category: 'Text & Data',
  },
  {
    id: 'color-palette-extractor',
    name: 'Color Palette Extractor',
    description: 'Extract a color palette from any uploaded image. Ideal for designers and developers.',
    href: '/tools/color-palette-extractor',
    icon: Palette,
    category: 'Image & Media',
  },
  {
    id: 'unit-converter',
    name: 'Unit Converter Online',
    description: 'Convert various units of length, weight, temperature, and more in real-time.',
    href: '/tools/unit-converter',
    icon: Ruler,
    category: 'Calculators',
  },
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    description: 'Quickly calculate percentages, percentage increase/decrease, and ratios.',
    href: '/tools/percentage-calculator',
    icon: Percent,
    category: 'Calculators',
  },
  {
    id: 'loan-emi-calculator',
    name: 'Loan / EMI Calculator',
    description: 'Calculate your Equated Monthly Installment (EMI) for loans.',
    href: '/tools/loan-emi-calculator',
    icon: Landmark,
    category: 'Calculators',
  },
  {
    id: 'qr-code-generator',
    name: 'Free QR Code Generator',
    description: 'Generate QR codes from text, URLs, or contact info in real-time. Free and easy to use.',
    href: '/tools/qr-code-generator',
    icon: QrCode,
    category: 'Generators',
  },
  {
    id: 'barcode-generator',
    name: 'Barcode Generator',
    description: 'Create and download various types of barcodes like Code128, EAN, and UPC.',
    href: '/tools/barcode-generator',
    icon: Barcode,
    category: 'Generators',
  },
  {
    id: 'random-number-generator',
    name: 'Random Number Generator',
    description: 'Generate random numbers within a specified range. Simple and secure.',
    href: '/tools/random-number-generator',
    icon: Sparkles,
    category: 'Generators',
  },
  {
    id: 'word-counter',
    name: 'Online Word Counter',
    description: 'Count words, characters, sentences, and paragraphs in your text instantly.',
    href: '/tools/word-counter',
    icon: Sigma,
    category: 'Text & Data',
  },
  {
    id: 'case-converter',
    name: 'Case Converter Tool',
    description: 'Instantly convert text to sentence case, lowercase, UPPERCASE, and Title Case.',
    href: '/tools/case-converter',
    icon: CaseSensitive,
    category: 'Text & Data',
  },
  {
    id: 'url-encoder-decoder',
    name: 'URL Encoder & Decoder',
    description: 'Encode and decode URLs and strings for safe use in web applications.',
    href: '/tools/url-encoder-decoder',
    icon: Link,
    category: 'Text & Data',
  },
  {
    id: 'age-calculator',
    name: 'Age Calculator Free',
    description: 'Calculate your exact age in years, months, and days from your date of birth.',
    href: '/tools/age-calculator',
    icon: Calendar,
    category: 'Calculators',
  },
  {
    id: 'bmi-calculator',
    name: 'BMI Calculator Tool',
    description: 'Calculate your Body Mass Index (BMI) using metric or imperial units.',
    href: '/tools/bmi-calculator',
    icon: Calculator,
    category: 'Calculators',
  },
  {
    id: 'password-generator',
    name: 'Strong Password Generator',
    description: 'Generate secure, random passwords with customizable length and character types.',
    href: '/tools/password-generator',
    icon: Lock,
    category: 'Generators',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview Online',
    description: 'Write and preview Markdown in a live, side-by-side editor. Ideal for developers.',
    href: '/tools/markdown-preview',
    icon: FileCode,
    category: 'Text & Data',
  },
  {
    id: 'json-formatter',
    name: 'JSON Formatter Online',
    description: 'Format, validate, and beautify your JSON data for readability and debugging.',
    href: '/tools/json-formatter',
    icon: Braces,
    category: 'Text & Data',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator Online',
    description: 'Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text input.',
    href: '/tools/hash-generator',
    icon: Hash,
    category: 'Generators',
  },
  {
    id: 'base64-encoder-decoder',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode data in Base64 format for easy and safe data transfer.',
    href: '/tools/base64-encoder-decoder',
    icon: Binary,
    category: 'Text & Data',
  },
  {
    id: 'lorem-ipsum-generator',
    name: 'Lorem Ipsum Generator',
    description: 'Generate placeholder dummy text for your designs and layouts with various options.',
    href: '/tools/lorem-ipsum-generator',
    icon: BookType,
    category: 'Generators',
  },
  {
    id: 'timezone-converter',
    name: 'Time Zone Converter',
    description: 'Easily convert times between different cities and time zones across the world.',
    href: '/tools/timezone-converter',
    icon: Clock,
    category: 'Calculators',
  },
];

export const toolMap = new Map(tools.map(tool => [tool.id, tool]));

export const categories: ToolCategory[] = Array.from(new Set(tools.map(tool => tool.category))).sort();
