
import type { LucideIcon } from 'lucide-react';
import {
  ImageIcon, FileText, Mic, Palette, Ruler, QrCode, Sigma, CaseSensitive, Link as LinkIcon,
  Calendar, Calculator, Lock, FileCode, Braces, Hash, Binary, BookType, Clock, Crop, Percent, Landmark,
  Barcode, Sparkles, Merge, RotateCw, Trash2, Split, Shield, SquarePen, FileScan, FileKey2, Beaker,
  FileCog, Paintbrush, Bot, Sun, Wand, Rows, Columns, MousePointer, UtilityPole, Webhook,
  NotepadText, CheckCheck, KeyRound, Globe, Component, ShoppingCart
} from 'lucide-react';

export const iconMap: { [key: string]: LucideIcon } = {
  'image': ImageIcon,
  'file-text': FileText,
  'notepad-text': NotepadText,
  'calculator': Calculator,
  'sparkles': Sparkles,
  'paintbrush': Paintbrush,
  'utility-pole': UtilityPole,
  'image-icon': ImageIcon,
  'crop': Crop,
  'palette': Palette,
  'component': Component,
  'bot': Bot,
  'merge': Merge,
  'split': Split,
  'trash-2': Trash2,
  'square-pen': SquarePen,
  'rotate-cw': RotateCw,
  'file-key-2': FileKey2,
  'file-cog': FileCog,
  'sigma': Sigma,
  'braces': Braces,
  'case-sensitive': CaseSensitive,
  'mic': Mic,
  'rows': Rows,
  'link-icon': LinkIcon,
  'binary': Binary,
  'file-code': FileCode,
  'webhook': Webhook,
  'percent': Percent,
  'landmark': Landmark,
  'calendar': Calendar,
  'ruler': Ruler,
  'lock': Lock,
  'qr-code': QrCode,
  'book-type': BookType,
  'hash': Hash,
  'barcode': Barcode,
  'wand': Wand,
  'key-round': KeyRound,
  'globe': Globe,
  'shield': Shield,
  'sun': Sun,
  'columns': Columns,
  'clock': Clock,
  'mouse-pointer': MousePointer,
  'shopping-cart': ShoppingCart,
};
