
import { SiteHeader } from '@/components/site-header';
import { SiteFooter } from '@/components/site-footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Disclaimer | Toolzen',
  description: 'Read the disclaimer for Toolzen. Our tools are provided for general informational purposes only. Your use of our services is at your own risk.',
  alternates: {
    canonical: '/disclaimer',
  },
  openGraph: {
    title: 'Disclaimer | Toolzen',
    description: 'Read the disclaimer for Toolzen. Our tools are provided for general informational purposes only. Your use of our services is at your own risk.',
    url: '/disclaimer',
    siteName: 'Toolzen',
    type: 'website',
    locale: 'en_US',
  },
  twitter: {
    card: 'summary',
    title: 'Disclaimer | Toolzen',
    description: 'Read the disclaimer for Toolzen. Our tools are provided for general informational purposes only. Your use of our services is at your own risk.',
  },
};

export default function DisclaimerPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <SiteHeader />
      <main className="flex-1 container mx-auto px-4 md:px-6 py-12">
        <Button asChild variant="ghost" className="mb-4">
            <Link href="/">
                <ArrowLeft className="mr-2 h-4 w-4" />
                Back to Home
            </Link>
        </Button>
        <Card className="max-w-3xl mx-auto bg-card/60 backdrop-blur-lg">
          <CardHeader>
            <CardTitle className="text-3xl font-serif">Disclaimer</CardTitle>
            <p className="text-muted-foreground pt-2">Last updated: August 18, 2024</p>
          </CardHeader>
          <CardContent className="prose dark:prose-invert max-w-none text-lg">
            <p>
              The information and tools provided by Toolzen ("we," "us," or "our") on toolzenweb.com (the "Site") are for general informational and utility purposes only. All information and tools on the Site are provided in good faith, however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or tool on the Site.
            </p>
            
            <h3 className="font-serif">No Professional Advice</h3>
            <p>
              The Site cannot and does not contain professional advice. The information is provided for general informational and educational purposes only and is not a substitute for professional advice. For example:
            </p>
            <ul>
                <li>The **BMI Calculator** does not provide medical advice. The information generated is not intended to diagnose, treat, or prevent any health problems. Always consult with a qualified healthcare professional for any health concerns or before making any decisions related to your health.</li>
                <li>The **Loan/EMI Calculator** does not provide financial advice. The calculations are for estimation purposes only and do not constitute a loan offer. Interest rates and loan terms vary by lender. Always consult with a qualified financial advisor before making any financial decisions.</li>
                <li>The **Password Generator** creates strong, random passwords, but it is your responsibility to store them securely using a trusted password manager. We are not liable for any security breaches resulting from improper password management.</li>
            </ul>
            <p>
                Accordingly, before taking any actions based upon such information, we strongly encourage you to consult with the appropriate professionals. The use or reliance of any information or tool contained on this site is solely at your own risk.
            </p>

            <h3 className="font-serif">"AS IS" and "AS AVAILABLE" Basis</h3>
            <p>
              All tools and services on Toolzen are provided on an "as is" and "as available" basis. We do not warrant that the tools will be error-free, uninterrupted, secure, or that they will meet your specific requirements. While we strive for accuracy, the output generated by our tools (e.g., compressed images, generated PDFs, calculated values, converted data) should be verified by you for accuracy and suitability for your intended purpose. We are not responsible for any errors, omissions, or inaccuracies in the results provided by the tools.
            </p>

            <h3 className="font-serif">Limitation of Liability</h3>
            <p>
              UNDER NO CIRCUMSTANCE SHALL WE HAVE ANY LIABILITY TO YOU FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF THE SITE OR OUR TOOLS OR RELIANCE ON ANY INFORMATION PROVIDED ON THE SITE. YOUR USE OF THE SITE AND YOUR RELIANCE ON ANY INFORMATION OR TOOL ON THE SITE IS SOLELY AT YOUR OWN RISK. THIS INCLUDES, BUT IS NOT LIMITED TO, LOSS OF DATA, LOSS OF PROFITS, OR ANY OTHER DIRECT, INDIRECT, CONSEQUENTIAL, OR INCIDENTAL DAMAGES.
            </p>
            
            <h3 className="font-serif">External Links Disclaimer</h3>
            <p>
              The Site may contain (or you may be sent through the Site) links to other websites or content belonging to or originating from third parties. Such external links are not investigated, monitored, or checked for accuracy, adequacy, validity, reliability, availability, or completeness by us. WE DO NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR THE ACCURACY OR RELIABILITY OF ANY INFORMATION OFFERED BY THIRD-PARTY WEBSITES LINKED THROUGH THE SITE. We will not be a party to or in any way be responsible for monitoring any transaction between you and third-party providers of products or services.
            </p>

            <h3 className="font-serif">Changes to This Disclaimer</h3>
             <p>
              We reserve the right to make additions, deletions, or modifications to the contents of this Disclaimer at any time without prior notice.
            </p>
          </CardContent>
        </Card>
      </main>
      <SiteFooter />
    </div>
  );
}
